name: Test Shards Merge

on: [push]

jobs:
  shard-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shard 1 tests
        run: |
          # Your test command for shard 1
          # Replace with your actual test command that generates a report (JUnit, etc.)
          npm run test -- --shard=1 > shard-1-report.xml
      - name: Upload shard 1 report
        uses: actions/upload-artifact@v2
        with:
          name: shard-1-report
          path: shard-1-report.xml

  shard-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shard 2 tests
        run: |
          # Your test command for shard 2
          # Replace with your actual test command that generates a report (JUnit, etc.)
          npm run test -- --shard=2 > shard-2-report.xml
      - name: Upload shard 2 report
        uses: actions/upload-artifact@v2
        with:
          name: shard-2-report
          path: shard-2-report.xml

  shard-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shard 3 tests
        run: |
          # Your test command for shard 3
          # Replace with your actual test command that generates a report (JUnit, etc.)
          npm run test -- --shard=3 > shard-3-report.xml
      - name: Upload shard 3 report
        uses: actions/upload-artifact@v2
        with:
          name: shard-3-report
          path: shard-3-report.xml

  shard-4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run shard 4 tests
        run: |
          # Your test command for shard 4
          # Replace with your actual test command that generates a report (JUnit, etc.)
          npm run test -- --shard=4 > shard-4-report.xml
      - name: Upload shard 4 report
        uses: actions/upload-artifact@v2
        with:
          name: shard-4-report
          path: shard-4-report.xml

  merge-reports:
    runs-on: ubuntu-latest
    needs: [shard-1, shard-2, shard-3, shard-4]  # Specify the jobs that need to be completed first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download shard 1 report
        uses: actions/download-artifact@v2
        with:
          name: shard-1-report
          path: ./reports/
      - name: Download shard 2 report
        uses: actions/download-artifact@v2
        with:
          name: shard-2-report
          path: ./reports/
      - name: Download shard 3 report
        uses: actions/download-artifact@v2
        with:
          name: shard-3-report
          path: ./reports/
      - name: Download shard 4 report
        uses: actions/download-artifact@v2
        with:
          name: shard-4-report
          path: ./reports/
      - name: Merge reports
        run: |
          # Example merging XML reports (JUnit format)
          # You can use a tool like 'xmlstarlet' or 'xsltproc' to merge the XML files
          # Here’s an example of simple concatenation (assuming reports are JUnit XML files):
          cat ./reports/shard-1-report.xml ./reports/shard-2-report.xml ./reports/shard-3-report.xml ./reports/shard-4-report.xml > ./reports/merged-report.xml
      - name: Upload merged report
        uses: actions/upload-artifact@v2
        with:
          name: merged-report
          path: ./reports/merged-report.xml
